### PR TITLE
Add installation of tinyxml.pc pkg-config file and fix license 

### PR DESCRIPTION
**Pull request by traversaro**
Both homebrew (https://github.com/Homebrew/homebrew-core/blob/1ffe361c1f30d8172f3bfce22a76ead45f082713/Formula/tinyxml.rb#L50) and debian (https://packages.debian.org/sid/amd64/libtinyxml-dev/filelist) versions of tinyxml ship a .pc file, so it would be convenient to ship it also in the conda-forge version. 

Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by traversaro** [comment]
@conda-forge-admin, please rerender

**Comment by traversaro** [comment]
@conda-forge-admin, please rerender

**Comment by traversaro** [comment]
The re-rendering error is:
~~~
$ conda smithy rerender -c auto
INFO:conda_smithy.configure_feedstock:Downloading conda-forge-pinning-2021.01.23.15.45.39
INFO:conda_smithy.configure_feedstock:Extracting conda-forge-pinning to C:\Users\STraversaro\AppData\Local\Temp\tmpmmbk2dqf
Setting build platform. This is only useful when pretending to be on another platform, such as for rendering necessary dependencies on a non-native platform. I trust that you know what you're doing.
WARNING:conda_build.config:Setting build platform. This is only useful when pretending to be on another platform, such as for rendering necessary dependencies on a non-native platform. I trust that you know what you're doing.
Setting build arch. This is only useful when pretending to be on another arch, such as for rendering necessary dependencies on a non-native arch. I trust that you know what you're doing.
WARNING:conda_build.config:Setting build arch. This is only useful when pretending to be on another arch, such as for rendering necessary dependencies on a non-native arch. I trust that you know what you're doing.
No numpy version specified in conda_build_config.yaml.  Falling back to default numpy value of 1.16
WARNING:conda_build.metadata:No numpy version specified in conda_build_config.yaml.  Falling back to default numpy value of 1.16
Adding in variants from internal_defaults
INFO:conda_build.variants:Adding in variants from internal_defaults
Adding in variants from C:\Users\STraversaro\AppData\Local\Temp\tmpmmbk2dqf\conda_build_config.yaml
INFO:conda_build.variants:Adding in variants from C:\Users\STraversaro\AppData\Local\Temp\tmpmmbk2dqf\conda_build_config.yaml
Adding in variants from argument_variants
INFO:conda_build.variants:Adding in variants from argument_variants
Adding in variants from C:\src\tinyxml-feedstock\recipe\conda_build_config.yaml
INFO:conda_build.variants:Adding in variants from C:\src\tinyxml-feedstock\recipe\conda_build_config.yaml
Traceback (most recent call last):
  File "C:\Users\STraversaro\Miniforge3\Scripts\conda-smithy-script.py", line 9, in <module>
    sys.exit(main())
  File "C:\Users\STraversaro\Miniforge3\lib\site-packages\conda_smithy\cli.py", line 613, in main
    args.subcommand_func(args)
  File "C:\Users\STraversaro\Miniforge3\lib\site-packages\conda_smithy\cli.py", line 419, in __call__
    self._call(args, tmpdir)
  File "C:\Users\STraversaro\Miniforge3\lib\site-packages\conda_smithy\cli.py", line 424, in _call
    configure_feedstock.main(
  File "C:\Users\STraversaro\Miniforge3\lib\site-packages\conda_smithy\configure_feedstock.py", line 1953, in main
    render_azure(env, config, forge_dir, return_metadata=True)
  File "C:\Users\STraversaro\Miniforge3\lib\site-packages\conda_smithy\configure_feedstock.py", line 1208, in render_azure
    return _render_ci_provider(
  File "C:\Users\STraversaro\Miniforge3\lib\site-packages\conda_smithy\configure_feedstock.py", line 607, in _render_ci_provider
    ) = conda_build.variants.get_package_combined_spec(
  File "C:\Users\STraversaro\Miniforge3\lib\site-packages\conda_build\variants.py", line 596, in get_package_combined_spec
    combined_spec = combine_specs(specs, log_output=config.verbose)
  File "C:\Users\STraversaro\Miniforge3\lib\site-packages\conda_build\variants.py", line 322, in combine_specs
    values = _combine_spec_dictionaries(specs, extend_keys=extend_keys, zip_keys=zip_keys,
  File "C:\Users\STraversaro\Miniforge3\lib\site-packages\conda_build\variants.py", line 294, in _combine_spec_dictionaries
    raise ValueError("variant config in {} is ambiguous because it\n"
ValueError: variant config in C:\src\tinyxml-feedstock\recipe\conda_build_config.yaml is ambiguous because it
does not fully implement all zipped keys, or specifies a
subspace that is not fully implemented. To be clear:
.. we did not find ['3.7'] from {'c_compiler': ['vs2017'], 'cxx_compiler': ['vs2017'], 'vc': ['14'], 'python': ['3.7']} in python:['3.6.* *_cpython', '3.7.* *_cpython', '3.8.* *_cpython']
(base)
~~~

**Comment by traversaro** [comment]
@conda-forge-admin, please rerender

**Comment by traversaro** [comment]
The re-rendering was successful after removing the `conda_build_config.yaml` file.

**Comment by traversaro** [comment]
@conda-forge/tinyxml the PR is now ready for review

**Comment by wolfv** [comment]
thx!

**Pull request merged**
