### PR TITLE
Enable Windows build

### PR DESCRIPTION
**Pull request by seanyen**
Checklist
* [x] Used a [fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by seanyen** [comment]
@conda-forge-admin, please rerender

**Comment by seanyen** [comment]
@conda-forge-admin, please rerender

**Comment by seanyen** [comment]
@conda-forge-admin, please rerender

**Comment by seanyen** [comment]
@conda-forge-admin, please rerender

**Comment by seanyen** [comment]
@conda-forge-admin, please rerender

**Review by jcarpent — APPROVED** [review]

**Comment by seanyen** [comment]
@conda-forge-admin, please rerender

**Comment by wolfv** [comment]
the only thing I am unsure about is that you manually changed things in `conda-forge.yml`. Would you mind force-pushing the original recipe + CMake changes again, and then re-rendering from there? 
I can also do it for you.

Btw. just in case you're interested in this, you can also install `conda-smithy` locally and re-render recipes by doing `conda smithy rerender` in the recipe folder.

**Comment by seanyen** [comment]
@conda-forge-admin, please rerender

**Comment by seanyen** [comment]
@wolfv I force pushed and clean up the commit history again, and for `conda-forge.yml`, I am following this [doc](https://conda-forge.org/docs/maintainer/conda_forge_yml.html) for the modification. Please take a look and see if it makes sense.

Btw, I am in favor of using the `conda-forge-admin` bot to rerender the recipe, in case my local environment doesn't match to the latest one.

**Comment by wolfv** [comment]
looks good to me, thanks for pointing me to the doc. In my experience with conda I never had to modify any of the auto-generated files, but if this was necessary then fine! Merging!

**Comment by wolfv** [comment]
btw the PR to staged recipes for catkin just got merged today -- it takes a little while until a proper feedstock is created and the package appears on conda. I'll try to push some other ROS packages tomorrow now that this one is through. Would be cool to have the ROS base by ROSCON, but not sure I can make it. 
I would be grateful if you have ideas on how to get windows support for the catkin package.

**Comment by seanyen** [comment]
@wolfv have you tried to make the conda recipe to be generated from `superflore` or `bloom`? I think that could motivate more package owner to try and release their package to `conda-forge` and potentially it can be automated.

**Pull request merged**
